import { Product } from './types'

// Default products - these represent the initial catalog
export const defaultProducts: Product[] = [
  {
    id: 'carnaval-1',
    name: 'Top Espalda Afuera',
    description: 'Top estilo carnaval con espalda descubierta, perfecto para festividades.',
    price: 30000,
    category: 'carnaval',
    colors: [
      { name: 'Naranja fluorescente', hex: '#ff2e0e' },
      { name: 'Amarillo fluorescente', hex: '#CCFF00' },
      { name: 'Rosa fluorescente', hex: '#FF1493' },
    ],
    image: '/placeholder-product.jpg',
    featured: true,
  },
  {
    id: 'carnaval-2',
    name: 'Top Metalizado',
    description: 'Top con acabado metalizado, ideal para looks de fiesta y carnaval.',
    price: 35000,
    category: 'carnaval',
    colors: [{ name: 'Metalizado', hex: '#BCC6CC' }],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'carnaval-3',
    name: 'Top Carnaval',
    description: 'Top vibrante para carnaval disponible en colores fluorescentes.',
    price: 30000,
    category: 'carnaval',
    colors: [
      { name: 'Naranja fluorescente', hex: '#ff2e0e' },
      { name: 'Amarillo fluorescente', hex: '#CCFF00' },
      { name: 'Rosa fluorescente', hex: '#FF1493' },
    ],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'blusa-1',
    name: 'Top Blusa',
    description: 'Blusa elegante de corte clasico, versatil para cualquier ocasion.',
    price: 35000,
    category: 'blusas',
    colors: [
      { name: 'Negro', hex: '#000000' },
      { name: 'Blanco', hex: '#FFFFFF' },
      { name: 'Rojo', hex: '#FF0000' },
    ],
    image: '/placeholder-product.jpg',
    featured: true,
  },
  {
    id: 'blusa-2',
    name: 'Top Asimetrico Un Hombro',
    description: 'Diseno asimetrico con un solo hombro para un look moderno y sofisticado.',
    price: 35000,
    category: 'blusas',
    colors: [
      { name: 'Rojo', hex: '#FF0000' },
      { name: 'Negro', hex: '#000000' },
      { name: 'Beige', hex: '#F5F5DC' },
      { name: 'Blanco', hex: '#FFFFFF' },
    ],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'blusa-3',
    name: 'Top Asimetrico sin Hombros',
    description: 'Top sin hombros con corte asimetrico, elegante y comodo.',
    price: 35000,
    category: 'blusas',
    colors: [
      { name: 'Rojo', hex: '#FF0000' },
      { name: 'Negro', hex: '#000000' },
      { name: 'Beige', hex: '#F5F5DC' },
      { name: 'Blanco', hex: '#FFFFFF' },
    ],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'blusa-4',
    name: 'Falda Shorts',
    description: 'Falda con shorts integrados para maxima comodidad y estilo.',
    price: 45000,
    category: 'blusas',
    colors: [
      { name: 'Malva', hex: '#E0B0FF' },
      { name: 'Blanco', hex: '#FFFFFF' },
    ],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'blusa-5',
    name: 'Crop Top',
    description: 'Crop top moderno y juvenil, ideal para combinar con faldas o jeans.',
    price: 35000,
    category: 'blusas',
    colors: [
      { name: 'Lila', hex: '#b695c0' },
      { name: 'Negro', hex: '#000000' },
      { name: 'Blanco', hex: '#FFFFFF' },
    ],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'blusa-6',
    name: 'Top Halter',
    description: 'Top con cuello halter, sexy y elegante para noches especiales.',
    price: 35000,
    category: 'blusas',
    colors: [{ name: 'Negro', hex: '#000000' }],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'blusa-7',
    name: 'Falda Globo',
    description: 'Falda con volumen estilo globo, unica y llamativa.',
    price: 45000,
    category: 'blusas',
    colors: [
      { name: 'Negro', hex: '#000000' },
      { name: 'Blanco', hex: '#FFFFFF' },
    ],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'blusa-8',
    name: 'Blusa Manga Larga',
    description: 'Blusa de manga larga con acabado elegante.',
    price: 40000,
    category: 'blusas',
    colors: [{ name: 'Negro', hex: '#000000' }],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'vestido-1',
    name: 'Vestido Corto Azul',
    description: 'Vestido corto en azul rey, perfecto para eventos y fiestas.',
    price: 75000,
    category: 'vestidos',
    colors: [{ name: 'Azul Rey', hex: '#4169e1' }],
    image: '/placeholder-product.jpg',
    featured: true,
  },
  {
    id: 'vestido-2',
    name: 'Vestido Corto Rojo',
    description: 'Vestido corto en rojo pasion, un clasico para cualquier ocasion especial.',
    price: 75000,
    category: 'vestidos',
    colors: [{ name: 'Rojo', hex: '#FF0000' }],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'vestido-3',
    name: 'Vestido Largo',
    description: 'Vestido largo elegante en negro, ideal para eventos formales.',
    price: 70000,
    category: 'vestidos',
    colors: [{ name: 'Negro', hex: '#000000' }],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'bano-1',
    name: 'Traje De Bano Cachetero',
    description: 'Traje de bano estilo cachetero, comodo y con estilo playero.',
    price: 40000,
    category: 'trajes-bano',
    colors: [
      { name: 'Naranja', hex: '#ED230D' },
      { name: 'Negro', hex: '#000000' },
      { name: 'Blanco', hex: '#FFFFFF' },
    ],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'bano-2',
    name: 'Traje De Bano Triangulo',
    description: 'Bikini triangulo con estampado de camuflaje, original y atrevido.',
    price: 38000,
    category: 'trajes-bano',
    colors: [{ name: 'Camuflaje', hex: '#AA77AA' }],
    image: '/placeholder-product.jpg',
  },
  {
    id: 'bano-3',
    name: 'Traje De Bano Hipster',
    description: 'Traje de bano estilo hipster en turquesa vibrante.',
    price: 40000,
    category: 'trajes-bano',
    colors: [{ name: 'Azul Turquesa', hex: '#5dc1b9' }],
    image: '/placeholder-product.jpg',
  },
]
